spring:
  application:
    name: priorityQueue
  datasource:
    url: jdbc:mysql://localhost:3306/priorityqueue
    username: root
    password: Vfr$3edc

  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_updates: true
          generate_statistics: true


  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin





